### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/quarto-revealjs-uaz#6]
Add instructions to use this template to README

**Comment by dlebauer** [comment]
looking forward to instructions - is the idea that this repository should be turned into a template? 

![image](https://user-images.githubusercontent.com/464871/189458013-3ee533bb-5806-4e76-a216-de98a9c2f5a1.png)

**Comment by Aariq** [comment]
There's a way to use templates with the quarto CLI, but I need to figure that out.
